
name: Pack files and release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i
    
      - name: Install FlexCli
        run: npm install -g @eniac/flexcli

      - name: Build Plugin
        run: npm run build

      - name: Pack Plugin
        run: npm run plugin:pack

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: com.jagk.apple_music.flexplugin
